################
### Language ###
################
language: bash

services:
  - docker

#####################
### Notifications ###
#####################
notifications:
  email: false

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

matrix:
  include:
  - env: PAPER_VERSION=1.8.8  JAVA_VERSION=8
  - env: PAPER_VERSION=1.9.4  JAVA_VERSION=8
  - env: PAPER_VERSION=1.10.2 JAVA_VERSION=8
  - env: PAPER_VERSION=1.11.2 JAVA_VERSION=11
  - env: PAPER_VERSION=1.12   JAVA_VERSION=11
  - env: PAPER_VERSION=1.12.1 JAVA_VERSION=11
  - env: PAPER_VERSION=1.12.2 JAVA_VERSION=11
  - env: PAPER_VERSION=1.13   JAVA_VERSION=11
  - env: PAPER_VERSION=1.13.1 JAVA_VERSION=11
  - env: PAPER_VERSION=1.13.2 JAVA_VERSION=11
  - env: PAPER_VERSION=1.14   JAVA_VERSION=11
  - env: PAPER_VERSION=1.14.1 JAVA_VERSION=11
  - env: PAPER_VERSION=1.14.2 JAVA_VERSION=11
  - env: PAPER_VERSION=1.14.3 JAVA_VERSION=11
  - env: PAPER_VERSION=1.14.4 JAVA_VERSION=11
  - env: PAPER_VERSION=1.15   JAVA_VERSION=11
  - env: PAPER_VERSION=1.15.1 JAVA_VERSION=11
  - env: PAPER_VERSION=1.15.2 JAVA_VERSION=11
  - env: PAPER_VERSION=1.16.1 JAVA_VERSION=11
  - env: PAPER_VERSION=1.16.2 JAVA_VERSION=11
  - env: PAPER_VERSION=1.16.3 JAVA_VERSION=11
  - env: PAPER_VERSION=1.16.4 JAVA_VERSION=11
  - env: PAPER_VERSION=1.16.5 JAVA_VERSION=16
